# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xt5hVJGQnBztgwaYLrOGZsyey0CjTAjB
"""

# 📌 Complete Autocorrect Tool Code (Google Colab)

# Install required libraries
!pip install textblob autocorrect

# Import libraries
from textblob import TextBlob
from autocorrect import Speller

# Initialize spell checker
spell = Speller(lang='en')

# Function to autocorrect using Autocorrect
def autocorrect_text(text):
    corrected_text = spell(text)
    return corrected_text

# Function to autocorrect using TextBlob
def textblob_correction(text):
    blob = TextBlob(text)
    return str(blob.correct())

# ----------- MAIN PROGRAM -----------

print("---- Autocorrect Tool (Demo Sentences) ----\n")

sample_sentences = [
    "I liek to lern machne learing",
    "Ths is an exmple of autcorect tool",
    "Arificial inteligence is the futre"
]

for sentence in sample_sentences:
    print(f"Original: {sentence}")
    print(f"Corrected (Autocorrect): {autocorrect_text(sentence)}")
    print(f"Corrected (TextBlob): {textblob_correction(sentence)}\n")


print("---- Interactive Autocorrect Tool ----\n")

while True:
    user_input = input("Enter a sentence (or type 'exit' to quit): ")
    if user_input.lower() == "exit":
        print("\nExiting Autocorrect Tool... Goodbye! 👋")
        break

    corrected_auto = autocorrect_text(user_input)
    corrected_blob = textblob_correction(user_input)

    print(f"\nOriginal: {user_input}")
    print(f"Corrected (Autocorrect): {corrected_auto}")
    print(f"Corrected (TextBlob): {corrected_blob}\n")